# Your Solution
# Your Solution
version: '3'
services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://sit722_part3_7xjc_user:c5pz0A5t53ODkjePvHQ4c5JpnxukHAKR@dpg-crcbh9dsvqrc73cht100-a.oregon-postgres.render.com/sit722_part3_7xjc
    restart: "no"

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://sit722_part3_7xjc_user:c5pz0A5t53ODkjePvHQ4c5JpnxukHAKR@dpg-crcbh9dsvqrc73cht100-a.oregon-postgres.render.com/sit722_part3_7xjc
    restart: "no"