# Your Solution
# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: duozhang123456.azurecr.io/book-catalog:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part3_7xjc_user:c5pz0A5t53ODkjePvHQ4c5JpnxukHAKR@dpg-crcbh9dsvqrc73cht100-a.oregon-postgres.render.com/sit722_part3_7xjc"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - port: 31000
      targetPort: 4000


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: duozhang123456.azurecr.io/inventory_management:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part3_7xjc_user:c5pz0A5t53ODkjePvHQ4c5JpnxukHAKR@dpg-crcbh9dsvqrc73cht100-a.oregon-postgres.render.com/sit722_part3_7xjc"


---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - port: 32000
      targetPort: 5000
 